### ISSUE TITLE
IE 11 - TypeError: Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by joelchu** [developit/preact#1084]
Build an SPA with preact.js (8.2.7) not using any react component, not using any preact-compact. 

Just pure preact + preact-router. 

But it doesn't even render on IE11. And when it render (on a login page) 

I get this error: TypeError: Object doesn't support property or method 'from'

The app works across platform and browsers, just not working on IE. Anyone encounter the same problem?

**Comment by marvinhagemeister** [comment]
Sounds like you are missing a polyfill for `Array.from`. As far as I know I'm not aware that we rely on `Array.from` in either of those libraries, but perhaps you have some third party dependency or your own app code which uses it.

See [mdn Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) for a Polyfill and more information.

**Comment by joelchu** [comment]
Also throw this two errors 

Possible Unhandled Promise Rejection: ReferenceError "Reflect" is undefined 


So I guess this is to do with the polyfill as well?

**Comment by marvinhagemeister** [comment]
@joelchu No, that is a separate error. The `Reflect` api is a fairly recent addition to JavaScript which isn't supported in old browsers. We're not relying on it either in any official preact-related library. All our libraries do support IE11+.

If you do want to use newer JavaScript features that are not supported older browsers, I'd highly recommend checking out [babel](http://babeljs.io/).

Closing, because this isn't about issues in preact.
