### ISSUE TITLE
Active state for buttons and others

### ISSUE THREAD

**Issue by SDemonUA** [developit/preact#1119]
Hello, I'm a bit new to this Preact/React stuff, and I'm trying to integrate it into already working platform with a lot of stuff in there. So, I faced with a question: how do you update/set active state on buttons/icons what open menus, like sub-menus. For now I use smth like this:

```javascript

render(h('componentWithMenuBtn', {onSomethingMenu:onMenu, ...otherProps }), parent, root);

function onMenu(id,/* other stuff */, component){
  /* menu widget code */
  // Here i've got component of Button or any else that support active state and waiting
  ...
  onShow: () => component.setState({ active:true })
  onHide: () => component.setState({ active:false })
  ...

  // And in case when menu items triggers ajax request it simply set:
  component.setState({ wait:promise })
}

**Comment by marvinhagemeister** [comment]
@SDemonUA For support questions I'd highly recommend joining our slack channel at https://preact-slack.now.sh/ . More people hangout there instead of here in our issue tracker.

Using `setState` for this is perfectly fine and often the easiest way to do so. If you have multiple components which need access to the same state you can either hoist the state up to the shared parent component or use a state-management library like unstated/redux/mobx/etc. It sounds like your setup is rather simple though, so `setState` should be more than enough :)
