### ISSUE TITLE
preserve css?

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [developit/preact#1144]
I don't want to see the following:

<img width="304" alt="screen shot 2018-06-13 at 12 35 42 pm" src="https://user-images.githubusercontent.com/39720421/41330477-51f8bf0a-6f06-11e8-8268-cc50ed5cabd9.png">

What I want is to be able to `import './style';` on a particular component and be able to reference the css class name from there, without the need for `style.myStyleClassName`. So basically, turn this:

```
import { h, Component } from 'preact';
import styles from './style';

export default class Header extends Component {
  render () {
    return (
      <header className={styles.whatever}>
        //...
      </header>
    );
  }
}
```

into this:

```
import './style';

import { h, Component } from 'preact';

export default class Header extends Component {
  render () {
    return (
      <header className="whatever">
        //...
      </header>
    );
  }
}
```

the css files should still be served the same way.

- In the `<head> `tag.
- Only when a component needs it.

**NOTE:** Usage with `sass`.

**Comment by marvinhagemeister** [comment]
@sprlwrksAprilmintacpineda Preact only deals with rendering and updating dom elements, it doesn't care which css solution is used on top of that. The webpack team or the issue tracker of the specific webpack loader you are using for sass/css is the right place to ask.

Closing, because this has nothing to do with preact.
