### ISSUE TITLE
Context question

### ISSUE THREAD

**Issue by angelochen960** [developit/preact#1195]
Hi,
trying out Preact, following code is supposed to show the user name in Child component, but it shows nothing, anything missing? thanks
```
function Child() {
    return (
        <p>child component {this.context.user}</p>
    )
}
class Myprovider extends Component {
    getChildContext() {
        return { user: 'Prect' }
    }
    render({ children }) {
        return children[0];
    }
}

class App extends Component {
    render(props, state) {
             return (
            <Myprovider>
                <h1> Parent </h1>
                <Child></Child>
            </Myprovider>
        )
    }
}

render(<App />, document.body)
```

**Comment by Kanaye** [comment]
There are actually two mistakes in your example.
1. Your `Child` doesn't extend `Component` and will therefore not have a `context` property.
Preact passes the context as the second argument to stateless components, so you can use the second argument as the context.

2. You are only returning the *first* child in your `Myprovider` which in this case is the `<h1> Parent </h1>`.
So the `<Child></Child>` will never be rendered. You can fix this by either returning all children wrapped in e.g. a `<div>` or by removing the `<h1>` from your `App`.

You example updated to return all children in `Mycomponent` and to use the second argument instead of `this.context`.
```javascript
function Child(props, context) {
    return (
        <p>child component {context.user}</p>
    )
}
class Myprovider extends Component {
    getChildContext() {
        return { user: 'Prect' }
    }
    render({ children }) {
        return <div>{children}</div>;
    }
}

class App extends Component {
    render(props, state) {
             return (
            <Myprovider>
                <h1> Parent </h1>
                <Child></Child>
            </Myprovider>
        )
    }
}

render(<App />, document.body)
```

Or you can view your example [here](https://preactjs.com/repl?code=import%20%7B%20Component%2C%20h%20%7D%20from%20%27preact%27%3B%0A%0Afunction%20Child(props%2C%20context)%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cp%3Echild%20component%20%7Bcontext.user%7D%3C%2Fp%3E%0A%20%20%20%20)%0A%7D%0Aclass%20Myprovider%20extends%20Component%20%7B%0A%20%20%20%20getChildContext()%20%7B%0A%20%20%20%20%20%20%20%20return%20%7B%20user%3A%20%27Prect%27%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20render(%7B%20children%20%7D)%20%7B%0A%20%20%20%20%20%20%20%20return%20%3Cdiv%3E%7Bchildren%7D%3C%2Fdiv%3E%3B%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20App%20extends%20Component%20%7B%0A%20%20%20%20render(props%2C%20state)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CMyprovider%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ch1%3E%20Parent%20%3C%2Fh1%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CChild%3E%3C%2FChild%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FMyprovider%3E%0A%20%20%20%20%20%20%20%20)%0A%20%20%20%20%7D%0A%7D%0A%0Aexport%20default%20App) within the preact repl.

**Comment by marvinhagemeister** [comment]
Accessing `context` via `this` only works for class-based components. Functional components get it passed directly as a standard argument:

```
function MyComponent(props, context) {
  return <p>{context.whatever}</p>
}
```

**Comment by angelochen960** [comment]
@Kanaye 
thanks for the sample, it works! now I change the Child to extend from Component so that it will have a context, but not working in this [example](https://preactjs.com/repl?code=import%20%7B%20Component%2C%20h%20%7D%20from%20%27preact%27%3B%0A%0Afunction%20Child(props%2C%20context)%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cp%3Echild%20component%20%7Bcontext.user%7D%3C%2Fp%3E%0A%20%20%20%20)%0A%7D%0A%0A%0Aclass%20Child2%20extends%20Component%20%7B%0A%20%20%0A%20%20%20%20render()%20%20%7B%0A%20%20%20%20%20%20%20%20%3Cp%3Echild%20component%20%7Bthis.context.user%7D%3C%2Fp%3E%20%0A%20%20%20%20%7D%0A%7D%0A%0A%0Aclass%20Myprovider%20extends%20Component%20%7B%0A%20%20%20%20getChildContext()%20%7B%0A%20%20%20%20%20%20%20%20return%20%7B%20user%3A%20%27Prect%27%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20render(%7B%20children%20%7D)%20%7B%0A%20%20%20%20%20%20%20%20return%20%3Cdiv%3E%7Bchildren%7D%3C%2Fdiv%3E%3B%0A%20%20%20%20%7D%0A%7D%0A%0Aclass%20App%20extends%20Component%20%7B%0A%20%20%20%20render(props%2C%20state)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CMyprovider%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ch1%3E%20Parent%20%3C%2Fh1%3E%0A%09%09%09%09%09%09%20%3CChild2%3E%3C%2FChild2%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FMyprovider%3E%0A%20%20%20%20%20%20%20%20)%0A%20%20%20%20%7D%0A%7D%0A%0Aexport%20default%20App) , what I'm missing here?

**Comment by Kanaye** [comment]
@angelochen960 
Your `Child2`s `render()` is not returning anything.
Change line 13 from 
`<p>child component {this.context.user}</p>`
to
`return (<p>child component {this.context.user}</p>);`
