### ISSUE TITLE
New feature: manipulate with className as a set, instead of a string

### ISSUE THREAD

**Issue by dvoytenko** [developit/preact#1295]
The `class` attribute is somewhat similar to `style` attribute: it's a string representation of a more sophisticated data structure. In the case of `style` it's a `CSSStyleDeclaration`, which is a map. In the case `class`, it's a proxy for the `classList: DOMTokenList`, which is basically a set.

I think it'd be pretty natural to treat `class` similar to `style` and would also reduce conflicts with web components, where a web component could set its own "internal" classes.

This is what it could look like:

```
<div class={['class1', 'class2', isOn ? 'class3' : '', isOn2 && 'class4']}>
  ...
</div>
```

It would work as following:

1. The array is expected to have a set of strings. False-y values (empty strings, `false`, `null`, etc) will be removed from the array before processing.
2. The new array state will be diffed against the new state and only the changed classes will be added/removed.
3. The `element.classList` will be used to add/remove classes.

Here's a little demo: https://codesandbox.io/s/9lx87xkqvo. It shows that updating the `class` via Preact currently overwrites classes the classes set by an emulated web component.

**Comment by kumarharsh** [comment]
One gotcha I found yesterday while writing some vanilla JS is that IE11 doesn't take multiple classes as an argument to `classList.add()`.

**Comment by wizzard0** [comment]
this is interesting, though i'd vote for using object instead of a class, like 
```
<a class={{...someClassesFromProps, class1: true, class2: isOn }}>...</a>
```
rationale: easier to compose classes from different sources, if you use a list there's no way to clear a class, and with object it's just a matter of a spread operator

**Comment by adjourn** [comment]
I tend to agree, there's `classnames` package but it adds so much pointless boilerplate into each component **but**.. this probably wouldn't align with the goals of Preact. 

1. `classnames` gzip is 371b (YUGE), Im sure it could be code-golfed to smaller size but still
2. it would be very different from React API and while I don't care, it's one of the selling points

**Comment by kidqueb** [comment]
https://github.com/lukeed/clsx does a lot of what is being suggested in an opt-in fashion for anyone landing here

**Comment by lukeed** [comment]
Thanks @kidqueb 🙇 That project evolved from `obj-str`, which is exactly what Preact 7.1 and below used to do. It was removed because it could be shimmed – see [here](https://github.com/lukeed/obj-str#preact)

You could use that code snippet still & attach `obj-str` for old Preact behavior, or attach `clsx`/`classnames`/whatever you want.

As for the `classList` point, I made [`classico`](https://github.com/lukeed/classico) because classList is not very well supported (eg, it doesnt go as far back as Preact can go) and IE doesn't behave like any other browser.

**Comment by adjourn** [comment]
We need a better place to gather up-to-date Preact stuff, awesome packages @lukeed. :+1:

**Comment by lukeed** [comment]
Thank you~ The Preact website is getting a lot of TLC for the next release, including docs!

**Comment by marvinhagemeister** [comment]
This is a neat idea and something that can be easily implemented via the suggestions by @lukeed above, or as a runtime hook:

```js
import { options } from "preact";

options.vnode = (vnode) => {
  let props = vnode.props;
  props.class = doSomething(props.class);
  return vnode;
}
```

Because it is so easy to shim this feature and users usually bring their own variant of `classnames`, `clsx`, etc it is very unlikely that something like that would be added back to core.

**Comment by dvoytenko** [comment]
I do realize that it's easy enough to manipulate a string. But I'd still stress: `classes` is a set data structure. Manipulating it as a string is very counterintuitive and rife with bugs. I think this should be the default (and maybe the only) way to manipulate classes.

**Comment by marvinhagemeister** [comment]
@dvoytenko I see where you're coming from and we had something like that in core as luke mentioned. We stripped it because it wasn't used that often and instead users used their own set-like implementation on top of ours. This is especially true for users coming from react.

Another aspect to consider is performance. Right now `class/className` is a simple assignment because that maps 1:1 to the DOM. We just need to call `setAttribtute` and are done. With an a `array` we'd always need to iterate over it and either serialize it to a `string` or use the `classList` api which would add quite a few bytes.

With the rise of `CSS-in-JS`, `CSS-Modules`, etc this feature would be redundant. All these solutions mostly set a single class on an element. For that a simple string suffices.

The cool thing about `preact` is that you can make it work for you exactly like you want to. By creating a custom `options.vnode` hook you can support any custom properties and modify them in any way before they are passed to the reconciler :+1: We use the `options.*` hooks quite a lot ourselves when experimenting with new features and even built the upcoming hooks addon for Preact X with it. You could even publish it on npm and make that approach more popular :100:
