### ISSUE TITLE
[Preact X] Not sync with existing dom nodes

### ISSUE THREAD

**Issue by weijarz** [developit/preact#1434]
<https://codesandbox.io/s/p5op59yp7m>
When click the 'Increment' button many times, the old dom nodes still exists.

**Comment by marvinhagemeister** [comment]
Thanks for the great bug report and the sandbox :tada: That looks indeed nasty! I can confirm the issue with provided sandbox and it's a great test case we should include in our test suite :+1: 

Wrapping `<DataViewer />` with a simple div works around that problem, so it seems like we seem to mess up child ordering in `diffChildren()`.

Probably related #1343 , #1323 , #1326

**Comment by joshuataylor** [comment]
I'm also seeing this for our app, using PreactRouter.

**Comment by developit** [comment]
I think I ran into this as well.

**Comment by douggr** [comment]
Hello all! I'm not sure if this is actually related, but this issue is the closest to my case. Nothing in the changelog is related to this, am I missing something here?

Isn't *this* supposed to render `<Footer/>` after the `<Router>` component? Awkwardly this doesn't work in codesandbox.io (https://codesandbox.io/s/6z2zzw5r73) so there's a repo linked bellow.

```js
import { h, Component } from 'preact';
import { Router } from 'preact-router';

import Footer from './footer';
import Header from './header';

// Code-splitting is automated for routes
import Home from '../routes/home';

export default class App extends Component {

  /** Gets fired when the route changes.
   *	@param {Object} event		"change" event from [preact-router](http://git.io/preact-router)
   *	@param {string} event.url	The newly routed URL
   */
  handleRoute = e => {
    this.currentUrl = e.url;
  };

  render() {
    return (
      <div id="app">
        <Header />
        <Router onChange={this.handleRoute}>
          <Home path="/" />
        </Router>
        <Footer />
      </div>
    );
  }
}
```

**Versions:**
  * preact: `^10.0.0-alpha.2`
  * preact-router: `^3.0.0`
  * node: `v10.15.3`
  * yarn: `1.15.2` / npm `6.4.1`

**Expected**:
```
HEADER
Home
FOOTER
```

**Result**
```
HEADER
FOOTER
Home
```

Example: https://github.com/douggr/preact-10-dom-bug

**Comment by damianobarbati** [comment]
Yes guys, I'm seeing this as well.
I have items rendered outside the root DOM node of the component where they are rendered.
Unable to reproduce it right-now, I'll try as soon as I can.

**Comment by damianobarbati** [comment]
@marvinhagemeister @developit right after I wrote my last comment I spotted the cause of the bug afflicting my app: using the `key` prop outside a loop cause unpredictable behaviour (preact-x)!
I'll open a new issue as soon as I can make the codesandbox,.

**Comment by marvinhagemeister** [comment]
@weijarz Good news: I can't reproduce this issue in `master` anymore :tada: :100:
