### ISSUE TITLE
[PreactX] No longer working with undom

### ISSUE THREAD

**Issue by staydecent** [developit/preact#1480]
I've been using undom for my tests in quite a few projects. I just started exploring hooks in one of my own branches, and realized latest PreactX does not work with undom.

I took the linked fiddle from undom, and replaced the preact resource with: http://npmcdn.com/preact@next

With that as the only change, the fiddle stops working:
https://jsfiddle.net/vu3qjarw/

I'm not sure if undom needs updating to implement some DOM features that PreactX now requires, or if PreactX needs updates to the render?

Perhaps this is better suited as on issue on the undom project? If so, let me know and I can recreate it there.

Thanks!

**Comment by marvinhagemeister** [comment]
yup this issue is better suited on the `undom` repo. We are very likely using some features of the DOM which `undom` doesn't stub out. That's hardly an issue in Preact. If you do create an issue on the `undom` repo, be sure to include the error message you are seeing in front of you. That way the maintainers don't have to waste precious time guessing what could have gone wrong and instead can spent the time actually fixing it.

**Comment by developit** [comment]
Update if anyone runs into this: I've patched the JSFiddle to work with Preact: https://jsfiddle.net/developit/9jzyv6we/
Undom was missing `.localName` and `.data` (developit/undom#32), but the breakage was actually due to a fix JSFiddle rolled out that enabled strict mode for JS.
