### ISSUE TITLE
[preact 10.0.0-alpha.4] Could preact x-alpha.4 use in production environment ?

### ISSUE THREAD

**Issue by diyijing** [developit/preact#1541]
I'd like to replace react with preact in order to impove the performance, my SPA built with Hooks + ErrorBoundary,

**Comment by JoviDeCroock** [comment]
Yes, you can do so by aliassing preact/compat in your webpack config:

```
resolve: {
  alias: {
    react: 'preact/compat',
    'react-dom': 'preact/compat',
  }
}
```

Try it out and let me know if it works out.

**Comment by marvinhagemeister** [comment]
The `alpha` tag in software development is used to signal that the provided software may contain bugs. Some of those are known, some of them may not be discovered yet. That's why the typical disclaimer for any alpha release is usually something like: "Do not use alpha software in production".

That said, there are a couple of users that messaged us who are using it already in production. We landed quite a few important fixes in the past weeks that fix some high priority bugs where Preact rendered an incorrect result with `Fragments`. The code in `master` right now feels very well tested and I'm hoping that there won't be much issues left to tackle after our next release.

Personally I'd wait for at least the beta phase before using it in production. Ultimately this is up to you though. If you do find any bugs please file an issue, so that our final release can be rock solid :+1:
