### ISSUE TITLE
Support react.default

### ISSUE THREAD

**Issue by laitine** [developit/preact#1569]
I'm trying to use a react library which uses a call to react.default.CreateContext but Preact does not support this case because preact.default doesn't exist. Implementing support for this would benefit compatibility. Using Preact version **10.0.0-beta.0**.

The following example of use works

```js
const preact = require('preact');

const test = preact.createContext({
  withPreview: true
});

console.log(test);
```

But the following does not work

```js
const preact = require('preact');

const test = preact.default.createContext({
  withPreview: true
});

console.log(test);
```

**Comment by Kanaye** [comment]
As stated in [Preact X Alpha 0 release notes](https://github.com/developit/preact/releases/tag/10.0.0-alpha.0) preact doesn't include a default export anymore for better treeshaking support.

`preact/compat` on the otherhand includes a default export for compatibility reasons.

So you probably should alias `react` to `preact/compat` anyways since only compat mimics most of reacts behavior.

**Comment by laitine** [comment]
Thanks for the info @Kanaye 👍
