### ISSUE TITLE
Missing `preact-render-to-string` dep in compat/server

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/preact#1601]
Extracted from #1417 by @jlaustill:

> I think I am running into the same thing, so I created a bare bones razzle 3 repo to test.  I am just trying to get compat in core to work with beta.1, nothing more.  So I removed everything I could and am just trying to render a single div with some text.  I added the alias to weback and babel.  I could very possibly be doing something wrong, so here's the repo to pull if you want to play.  

> [razzle3-preact-x](https://github.com/jlaustill/razzle3-preact-x)

> EDIT:
> I created a branch no-mo-compat and converted to preact and it is working, so I'm thinking this is just an issue with preact/compat at this point.

**Comment by marvinhagemeister** [comment]
Ok, so the issue is caused by `compat/server.js` importing `preact-render-to-string` but the latter not being declared anywhere as a dependency. As a workaround the package can be added manually to the project's `package.json`.

Adding that to core would cause a circular dependency. I'm not sure how well `npm` or `yarn` handle that. It could be an argument in favor of moving `preact-render-to-string` into core.

**Comment by marvinhagemeister** [comment]
Thinking about it some more another option would be to wrap the `require` call in a `try/catch` and print a helpful message that `preact-render-to-string` needs to be installed.

**Comment by jlaustill** [comment]
Ok, that did the trick!  It seems to me that if you can't use compat without preact-render-to-string it makes more sense to move it into core.  If there are use cases where you can use compat without it, then maybe not.  I like the try/catch idea for the latter.

After installing that, react-router-dom throws an error about React not being defined if I try to add it back in, but I feel like that is probably a separate issue related to versions since react-router is supposed to support preact since v4 I believe.  

I pushed up the addition of preact-render-to-string so it now successfully renders, progress :)  Anyone can clone that now and start playing with react-router-dom or anything else if they want a starting point.

**Comment by krutoo** [comment]
i have same issue

in my project there is just wepback for building and `express` with `preact/compat`

installing `preact-render-to-string` as project dependency not resolves error
