### ISSUE TITLE
There is no way to update vnode props

### ISSUE THREAD

**Issue by NicHaley** [developit/preact#1640]
Preact offers a handy way to inject props into an element via the second parameter of `createElement`. However, there appears to be no method to update these props in a way that causes properties to propagate to child components.

In order to inject starting props and have them modifiable, I currently need to set state equal to props of the entry component.

eg.
```
constructor(props) {
    super(props);

    const {
      myProp
    } = props;

    this.state = {
      myProp,
      ...

```
Then, I would `setState` to perform future state changes.

I would much prefer to modify props directly.

**Comment by robertknight** [comment]
The lack of a method to update props is an intentional part of the way React's APIs work, and Preact is a lightweight implementation of those APIs.

The way React works, elements returned by `createElement` are immutable. You don't modify props, instead you [render a new element](https://reactjs.org/docs/rendering-elements.html#updating-the-rendered-element) into the same container DOM node.

If you are new to React and Preact, I would highly recommend reading through React's [Main Concepts](https://reactjs.org/docs/hello-world.html) guide. The principles apply equally well to Preact.

**Comment by NicHaley** [comment]
Yes makes sense!
