### ISSUE TITLE
General JSX Transformer

### ISSUE THREAD

**Issue by calebmer** [developit/preact#178]
Great project! I made a general JSX transformer, [babel-plugin-transform-jsx](https://www.npmjs.com/package/babel-plugin-transform-jsx) if you are interested in recommending that and avoiding `/* @jsx h */` comments and even repetitive imports.

**Comment by developit** [comment]
Nice work.  Any chance you'd be interested in making the property names configurable?  Preact VNodes use `nodeName` instead of `elementName` to match the DOM's API, but otherwise everything else would be identical.  That would mean people could use the plugin without modification to their code:

```js
{
  "plugins": [
    ["transform-jsx", { "function": "h", "useVariables": true }]
  ]
}
```

Or another thought - provide a "to hyperscript" option.  Preact's `h()` is intentionally identical to the hyperscript spec in order to be interoperable.  That way people could use `babel-plugin-transform-jsx` with preact, [vhtml](https://git.io/vhtml) and [hyperscript](https://github.com/dominictarr/hyperscript) right out of the box!  Perhaps that warrants a wrapper plugin, I'm not sure.  Curious to hear your thoughts - I would love to encourage everyone to understand the relationship between JSX and hyperscript a bit better, this could be a neat way to promote that.

**Comment by ForsakenHarmony** [comment]
@calebmer

**Comment by NekR** [comment]
I do this in webpack:

Babel loader:

```js
{
  loader: 'babel',
  test: /\.jsx?$/,
  exclude: /node_modules/,
  query: {
    cacheDirectory: true,
    presets: ['es2015'],
    plugins: [
      'transform-class-properties',
      ['transform-react-jsx', {
        pragma: 'jsx'
      }]
    ]
  }
}
```

Provide plugin:
```js
new ProvidePlugin({
  jsx: resolve('src/jsx.js'),
})
```

and `jsx.js`:
```js
const preact = require('preact');
module.exports = preact.h;
```

This way I don't need to define any pragma nor import Preact everytime when I need to use JSX. Probably makes sense to provide `Component` this way too.

**Comment by developit** [comment]
Nice! Might steal that.

**Comment by ForsakenHarmony** [comment]
would be nice if you could inline that somehow, not requiring the extra file

but I don't think my IDE or ESLint would agree with providing Component that way

**Comment by gdub22** [comment]
I just had a PR merged into webpack to eliminate that extra file
https://github.com/webpack/webpack/pull/3597

So in the next webpack release you can just do:

```js
new ProvidePlugin({
  jsx: ['preact', 'h']
})
```

**Comment by ForsakenHarmony** [comment]
@gdub22 very nice

**Comment by NekR** [comment]
> would be nice if you could inline that somehow, not requiring the extra file

It can be this way right now:
```js
new ProvidePlugin({
  preact: 'preact'
})
```

```js
{
  loader: 'babel',
  test: /\.jsx?$/,
  exclude: /node_modules/,
  query: {
    cacheDirectory: true,
    presets: ['es2015'],
    plugins: [
      'transform-class-properties',
      ['transform-react-jsx', {
        pragma: 'preact.h'
      }]
    ]
  }
}
```

> I just had a PR merged into webpack to eliminate that extra file

That's great!

But anyway, I'm totally fine with an additional file since it doesn't harm anything for me.

**Comment by NekR** [comment]
@developit 
> Nice! Might steal that.

Take it! Take it! 😄

**Comment by ForsakenHarmony** [comment]
well, yeah, I'm currently using the imports-loader

```
['transform-react-jsx', { pragma: 'preact.h' }]
```

```
{
  test  : /\.jsx$/,
  loader: 'imports-loader',
  query : {
    preact: 'preact',
  },
}
```

but just h will be nice with the next version of webpack

**Comment by developit** [comment]
I think we can close this out now - there are 3 or 4 great solutions including the original posted here :)

**Comment by felipenmoura** [comment]
Just to let it here.
I used this to make it work:

```
{ "pragma": "require('preact').h" }
```
