### ISSUE TITLE
input type="file" weird behavior

### ISSUE THREAD

**Issue by kruczy** [developit/preact#187]
It seems that reused input elements with type "file" do not clear their selected file correctly
see: http://jsfiddle.net/mnypy1do/3/

also if you explicitly do: `<input type="file" value=""/>` (http://jsfiddle.net/mnypy1do/4/)
the same thing happens

I don't know what the proper behavior here should be, probably the best would be to pass in the `FileList` back into the input via `files` prop when something gets selected

The only problem is that getting an empty `FileList` is not an obvious thing, can't just do `new FileList()`, you have to
```
var input = document.createElement("input");
input.type = "file";
var emptyFiles = input.files;
```

see: http://jsfiddle.net/mnypy1do/5/

and passing null wont worke either, unless there would be special handling for this (input.files = null) does nothing

Any thoughts on this?
Thanks

**Comment by developit** [comment]
Ahh interesting. So it's actually not the recycler, but just the reconciliation being totally unaware of `.files` because it is state coming from the DOM itself.  To me this is sort-of an "accidentally similar trees" type situation, and for those I tend to just throw keys onto the afflicted elements or their roots, causing the diff to treat them as independent (but still preserve and recycle them independently of each other).

Here's an example of keys fixing the issue: http://jsfiddle.net/developit/f2gfz7aL/

That being said, this behavior is definitely a bit odd.  We normalize input values in a similar way, it just doesn't apply for `type="file"` (the input element is insane).

The tricky thing is that Preact can't really know that `render()` is giving it a separate tree of nodes (without adding keys as the hint).  As far as the library is concerned, the following produce identical output:

```js
<div>
  {this.state.show && <div class="one">
    One
    <input type="file" name="one" />
  </div> }
  {!this.state.show && <div class="two">
    Two
    <input type="file" name="two" />
  </div>}
</div>

// ^ is identical to:

<div>
  <div class={this.state.show ? 'one' : 'two'}>
    { this.state.show ? 'One' : 'Two' }
    <input type="file" name={ this.state.show ? 'one' : 'two' } />
  </div>
</div>
```

... interestingly, we'd expect the latter to preserve the FileList, but the former to reset it.  I'm not sure how to resolve that other than by adding keys.

Super interesting case though. What do you think?

**Comment by kruczy** [comment]
When looking at it like this it makes it even more interesting

I did not really notice the other input issues, I pass the value in every time

In my apps case there is no show/hide it is routing and I have a page with a file input that if you use the page twice in one session it will have that previous file selected in it even if I use `key`, In that case I could just do the trick of setting the state with an empty file list and passing it with `files`

maybe it should be cleared when mounting and not cleared when applying a diff to an already mounted element?

**Comment by developit** [comment]
Yes, that seems very reasonable. I'm wondering if this should just be a recursive setting of value on unmount?

**Comment by kruczy** [comment]
ya, unmount makes more sense than mount :)

this could work for all input types hopefully not only file

Could this be a breaking change for some applications? For example if you have a tabbed view someone could expect inputs not to be cleared even though they were unmounted? Is it enough to let people know that it is the case?

**Comment by developit** [comment]
It'll be breaking, yeah.  I'd like to check if React does this, though they don't recycle components across mounts, so this change would likely bring us closer to their behavior.  The change can just go into `5.0.0-betaX`, there are still a few things that need to be worked out before I roll that over to be the current major version.

**Comment by kruczy** [comment]
react version: https://jsfiddle.net/5cuaptd6/2/

**Comment by developit** [comment]
@kruczy What did we end up deciding on this?  I'm hesitant to add the per-render indeterminate value clearing because of the crazy performance hit.  Think it's worth just saying "use keys or components" or something along those lines?

**Comment by kruczy** [comment]
I have a Component wrapper for all inputs I use
I just added:
```javascript
componentDidUnmount() {
	if (this.props.type === "file") {
		this.base.querySelector("input").value = "";
	}
}
```
and it fixes the problem

It would be good to document it somewhere if there will be no change to the code so anybody that hits this will know what is happening

**Comment by developit** [comment]
Hey @kruczy - I think I landed on a happy medium for this:  your first example of passing `value=""` really should have been resetting that input, otherwise the virtual DOM is then out of sync with the actual DOM.

In the latest beta (as of `5.0.1-beta.15`), that now works!  Demo:
http://jsfiddle.net/developit/mnypy1do/6/

I think I'll close this one out for now, but I'd love to continue investigating options for resetting inputs automatically.

**Comment by kruczy** [comment]
Cool, thanks alot!
