### ISSUE TITLE
V8 deopts `diff`

### ISSUE THREAD

**Issue by marklundin** [developit/preact#193]
Useful to know but It seems V8 tries to optimise the [diff](https://github.com/developit/preact/blob/ee58240bd8b2db496c8877a35543615b1ea82d8a/src/vdom/diff.js#L19) function, but bails out with the ['Optimized too many times'](https://github.com/GoogleChrome/devtools-docs/issues/53#issuecomment-145192013) reason. You can test this by running the profiler in Chrome and checking the Timeline.

Not sure what the cause of this could be, but I might do a little more digging. Would be great to open this up to the optimising compiler :)

**Comment by developit** [comment]
@marklundin Is there a specific demo or repro you are seeing the de-opt in?  Diff accepts a lot of different inputs, which means it tends to ride on the limits of V8's IC size, so I imagine there are some cases where that function switches from being polymorphic to megamorphic, depending on how Preact is used.  I'm not seeing a de-opt in [dbmonster](http://developit.github.io/js-repaint-perfs/preact/), but perhaps that demo is not stress-testing varied `diff()` inputs enough.

Interesting little factoid while you're digging around - one of the reasons `diff()` is relatively small and most of the diffing is handled by `diffNode()` / `diffAttributes()` is because it's difficult to control inputs to `diff()` itself - it accepts a DOM node as one of its arguments, and DOM nodes have wildly varying shape (unfortunate really).  My hope in separating the two was that it would be possible to only pass on things like `.childNodes` to `diffNode()` from `diff()`, which always has the same type.

Thanks for the extra eyes on performance, by the way! :)

**Comment by developit** [comment]
IRHydra is awesome, been using it to optimize for a few months. There are 2 or 3 functions in Preact that still hard de-opt, it'd be great to have another set of eyes looking for reasons.

**Comment by developit** [comment]
@marklundin Big thanks for pointing this out - I tried to strip back the use of deeply nested (dom) objects in some of the diff methods in 32c8aca and I think it should address that de-opt.

What should we do with this issue?  I like to have performance visibility, but I don't have anything on hand that I can try to further optimize `diff()`.  Maybe set up a performance backlog of some kind?  I would love to have more performance metrics/tests in the suite - there are [only two](https://github.com/developit/preact/blob/master/test/browser/performance.js) right now, but they have been immensely useful for catching performance regressions.

**Comment by marklundin** [comment]
This looks great, V8 is no longer bailing out of the diff. I think it's safe to close this off but agree it would be great to keep an eye on these types of things

**Comment by developit** [comment]
Great! 🎉
