### ISSUE TITLE
Possible Performance Improvement: DocumentFragment?

### ISSUE THREAD

**Issue by amilajack** [developit/preact#203]
I've been looking into `DocumentFragment` recently and it looks like a promising way of improving performance:

[http://ilikekillnerds.com/2015/02/stop-writing-slow-javascript/](http://ilikekillnerds.com/2015/02/stop-writing-slow-javascript/) (skip to the DocumentFragment section)

Basically, it allows the mutation of the DOM in a way that batches calls (somewhat similar to requestAnimationFrame)

Thoughts?

**Comment by developit** [comment]
Hi @amilajack - I actually just removed the usage of DocumentFragment from preact as a size savings measure, and because for whatever reason it was making things slower (https://esbench.com/bench/5756062bdb965b9a00965ae2). It might have been related to the particular way the nodes were being a though?

That bench does show another thing of interest though: for large sets of elements being appended to an attached DOM, DocFrag can reduce the overall time. But for elements being appended to an inactive DOM (eg if the parent or grandparent is not yet appended), it seems to be slightly slower (crazy!).

I believe the majority case in preact right now is that we append to an inactive DOM, but that's something worth testing for sure. 

Your second point is interesting too - preact has always debounced DOM updates, but around 4.0 switched from requestAnimationFrame to a tighter async deferral. I have been super curious if this had more dramatic effects on repaint speed than intended.

**Comment by developit** [comment]
Forgot to point to the commit:
https://github.com/developit/preact/commit/7b79e8313c987df108ca12f65553a3571d5aaeb6

**Comment by amilajack** [comment]
The note about the inactive DOM is very interesting. And what is the async deferral method that preact switched to?

**Comment by leeoniya** [comment]
@amilajack you may find this discussion informative: https://github.com/trueadm/inferno/issues/223

**Comment by amilajack** [comment]
@leeoniya Thanks!
