### ISSUE TITLE
image's onLoad triggered on each re-render

### ISSUE THREAD

**Issue by ascrazy** [developit/preact#222]
Hi guys,

I wanted to create component which displays spinner while image (img tag) is loading and then displays image itself. So I've created component which binds img's onLoad and onError events and does setState in callbacks. But looks like there's a bug which causes onLoad callback to be called on each re-render.

I've created a simple jsbin which demonstrates the problem: https://jsbin.com/jovifeqiji/1/edit?js,output
I modified the approach a little because original approach (setState from onLoad callback) hangs browser without any chance to debug it.

The interesting thing about this is that native event listener is triggered also. My first idea was that preact creates  a new img node on each render, but then I realized that it's the same node (===, reference compare) in each call of callback.

**Comment by developit** [comment]
Hi @ascrazy - thanks for the report. I tested and the issue doesn't seem to be present in Preact 5:
https://jsbin.com/cekogohuto/edit?js,console,output

The reason for the repeated loads in Preact 4 and prior was that the digging algorithm gave preference to resolves DOM properties when comparing previously applied props. If the image URL you specify isn't identical to the _final_ URL of the image (eg: if there are redirects, or you use any form of relative URL), then your URL was seen as being different from `img.src` on every render. This meant preact would re-assign the `src` prop, which triggers the full image load process. That's why you are seeing the native event too. 

My suggestion would be to use Preact 5 (`preact@beta`) for everything at this point. It's more stable than 4 and contains a lot of big fixes. I will likely be rolling it out as the stable (non-beta) version this week. 

Let me know if I missed anything! 🙊

**Comment by developit** [comment]
@ascrazy Closing this out for now since I'm certain this is solved in the beta.  Let me know if I'm wrong! :)
