### ISSUE TITLE
License / Patents

### ISSUE THREAD

**Issue by freynolds** [developit/preact#244]
How does preact compare to react patent deal [[link]](https://github.com/facebook/react/blob/master/PATENTS) where facebook reserves it's write to revoke the use of react if you compete with them?

My regards!
Francis.

**Comment by developit** [comment]
Hi @freynolds - Facebook has discussed this extensively in public and even modified the terms of the patent grant in order to make it clear their intent is not anti-competition.  The terms in their patent grant actually specifically state that the grant is revoked only when action is taken to initiate or join a patent claim against Facebook.  Since Preact is an independent Open Source project and not owned by a company, there would never be grounds to make a patent assertion even if there were concepts in Preact considered to be patent-worthy.

On a personal note, I'm happy Facebook has been transparent and considerate in this matter.  Preact certainly wouldn't exist without the amazing work and ideas Facebook realized in React, and we've all benefitted from their efforts to promote the React ideology and assemble a great community.

Let me know if that answers your question. Cheers!

**Comment by c2h5oh** [comment]
In the current form of patent grant it's a non-issue:

> Facebook, Inc. ("Facebook") hereby grants to each recipient of the Software ("you") a perpetual, worldwide, royalty-free, non-exclusive, **irrevocable** (subject to the termination provision below) 

Emphasis mine, means: Facebook can't terminate the licence at will or at all for that matter, unless termination provision is triggered.


> The license granted hereunder will terminate, automatically and without notice, if you

Provision is triggered automatically if one of the listed events occurs.

> initiate [...] any Patent Assertion:
> against Facebook [...]

You sue Facebook for patent infringement

> against any party if such Patent Assertion arises [...] from any software, technology, product or service of Facebook [...]

You sue someone else for patent infringement in software, tech or product provided by Facebook (ie because they use react)

> against any party relating to the Software
 
self-explanatory 

This is followed by an exception to the termination clause: if you you don't start the fight (if you counter-sue in response of the same claim being made against you it's ok)

**Comment by developit** [comment]
Thanks for the awesome breakdown @c2h5oh!

**Comment by developit** [comment]
I think we can close this issue as there has been consensus on the subject for a while. By all means though, I'm happy to continue the discussion.

**Comment by freynolds** [comment]
Thanks @c2h5oh @developit for the speedy response!
Glad to hear both things, first that preact is completely autonomous and the clarification about react patent grant.
Very helpful,
My regards

**Comment by bestwestern** [comment]
@c2h5oh does your explanation hold for React it self as well?
I make a super startup, company X wants to buy but doesn't dare because I use React/Preact and they're considering suing Facebook because of something else.

**Comment by c2h5oh** [comment]
We were discussing patent grant/licence that most Facebook open source projects are released with. Any patent lawsuit against Facebook (any patent) or a patent against a 3rd party over a patent relevant to FB open source project automatically revokes the licence. 

It's not just large corpo that take an issue with that: https://react.jsnews.io/apache-foundation-bans-use-of-facebook-bsdpatents-licensed-libraries-like-reactjs/

**Comment by bestwestern** [comment]
To me it seems that the question is:
1. Did React have the bad license when Preact was created?
2. If so is Preact so similar to React that the license is carried over
If both of the above is yes I am afraid that:
1. the scenario I described above holds for Preact as well
2. The Preact license file should be changed..

**Comment by developit** [comment]
1. yes
2. no
3. ?
4. Preact is MIT-licensed. There is no reason to change this.
