### ISSUE TITLE
Event capturing

### ISSUE THREAD

**Issue by i-like-robots** [developit/preact#266]
For the most part it is fine to skip the 3rd argument of `addEventListener` but some event types do not bubble - which creates a dilemma when using event delegation (for example, to avoid passing callbacks down the component tree).

I've created some very simple demos here:
- Vanilla JS http://codepen.io/anon/pen/PzXvVE
- React v15.3.0 http://codepen.io/anon/pen/QEPWNx
- Preact v5.7.0 http://codepen.io/anon/pen/YWrzWG

~~All synthetic events in React bubble (or at least _appear_ to do so) so this can create some incompatibilities when switching to Preact.~~

_UPDATE:_ React explicitly supports capturing by appending `Capture` to the attribute, E.G. `onClick` would become `onClickCapture` https://facebook.github.io/react/docs/events.html#supported-events and certain events are set to capture automatically (inc. focus and blur).

I'm not fully aware of the ramifications that changing [this line](https://github.com/developit/preact/blob/705fbbb749cce0fc0f27a3253d4d89ef4780f30a/src/dom/index.js#L61) would be. Perhaps it may be preferable to check the event type against a capturing whitelist.

I'm happy to help implement any changes, even if it's just a note in the docs 😄

**Comment by developit** [comment]
Ahh, thanks for raising this. I actually ran into this when looking into event cancellation issues a while back, and passing `true` for the third `useCapture` argument would have been an easy fix (ended up with a workaround).

I think it might be worth trying, since most use-cases are unaffected by the change, and some use-cases are fixed by it as you showed.

**Comment by i-like-robots** [comment]
I've done some further digging into this and it appears somewhere within React it decides to enable capturing for only some events. For instance given the following component:

```jsx
module.exports = (props) => (
  <div
    onFocus={props.handleFocus}
    onBlur={props.handleBlur}
    onChange={props.handleChange}
    onClick={props.handleClick}>
    <input />
  </div>
)
```

The following event listeners are attached:

![screen shot 2016-08-16 at 10 29 43](https://cloud.githubusercontent.com/assets/271645/17694651/b75bd610-639c-11e6-98da-090fc0c29c37.png)

**Comment by developit** [comment]
@i-like-robots Interesting - I guess this has to do with their use event delegation, since these are all attached globally.

Side note: I wasn't aware of `on**Capture`!  Think it's worth implementing in `preact`, or is that a `preact-compat` thing?  I don't imagine it's widely used if this is the first time I've seen it come up.

**Comment by i-like-robots** [comment]
I would think `preact-compat` - I've never seen it before either!

**Comment by i-like-robots** [comment]
I've asked around and had some input as to why this may be a _bad_ idea in some cases and why a whitelist may be preferable.

If all listeners are triggered at the capture phase then calling `preventDefault()` within the callback of an _inner_ node listener will not stop it from reaching an _outer_ node listener.

However, it can be sensible (preferable?) to use capture for some events, like those previously mentioned... and perhaps [a few more](https://github.com/ftlabs/ftdomdelegate/blob/master/lib/delegate.js#L96-L98).

(Thanks to @matt-andrews for refresher course)

**Comment by developit** [comment]
I think that makes more sense - I was worried about swapping to capturing phase for things like `click`, because there are definitely people invoking `stopPropagation()` on those types of events, expecting them not to bubble (up).  The events in the whitelist you linked to aren't bubbling events anyway, so I think it'd be alright to silently switch those over to `useCapture`.
