### ISSUE TITLE
whether the linkState can be used out of render func

### ISSUE THREAD

**Issue by evilemon** [developit/preact#272]
![image](https://cloud.githubusercontent.com/assets/13042865/17697913/6288dd7e-63ea-11e6-886c-38c4ff81a692.png)
how can i use the linkState ?

**Comment by developit** [comment]
Hi @evilemon - that's actually a little different than how `linkState` works.  Calling `this.linkState()` creates and returns an event handler for you.  Normally you would just pass that handler directly as an `on*` prop (as you have in the other examples), but if you want to use it outside of that, you'll need to call the returned handler.  Also - one note in your example:  the value of `this` within your `handleChange()` method will actually be the `HTMLInputElement` it was bound to because there is no autobinding in ES2015 class components.  An alternative declaration syntax is below:

```js
class Foo extends Component {
  // declaring your method this way fixes the value of "this":
  handleChange = e => {
    // create the linking handler:
    let handler = this.linkState('test');
    // call the handler directly:
    return handler(e);
  };

  render() {
    return (
      <form>
        <label>
          test Input:
          <input value={test} onInput={this.handleChange} />
        </label>
      </form>
    );
  }
}
```

This might be useful if you want to modify the value from the input prior to setting it as state.  However, it's also quite easy in that case to use `setState()` directly - you just lose the loose DOM coupling:

```js
  handleChange = e => {
    this.setState({ test: e.target.value });
  };
```

Hope that helps explain things!  I'll close the issue out since I think this covers everything, but please feel free to keep chatting.  I think `linkState()` needs a little more documentation of its own, too.

**Comment by evilemon** [comment]
thx, it really works. And i wonder whether linkState in preact is similar to the Two-Way Binding in react (LinkedStateMixin).

**Comment by evilemon** [comment]
thx, it really works!
