### ISSUE TITLE
is componentDidUnmount supported by preact ?

### ISSUE THREAD

**Issue by akiran** [developit/preact#288]
componentDidUnmount is mentioned in readme.
But this life cycle method is not available in react.

**Comment by developit** [comment]
It is currently supported, yes. I dont believe it is widely used though, might be time to get rid of it.

**Comment by povrazor** [comment]
(I'm assuming **The Wreckoning** is stuff that will be removed?)

I'm using `componentDidMount` and `componentDidUnmount` to wrap some calls that set `document.body` events. While the component is visible I need those events set, but as soon as its gone, I don't.

**Comment by developit** [comment]
heh - yeah good catch. `componentDidMount()` is definitely sticking around forever, but you should convert those to `componentDidUnmount()` calls to `componentWillUnmount()` - they actually get called at basically the same time, hence the deprecation of `componentDidUnmount()`.

**Comment by developit** [comment]
Ping me on Gitter if that's confusing - should be safe to switch.

**Comment by povrazor** [comment]
Makes sense, easy fix. I just wasn't following the reason for the deprecation.

**Comment by developit** [comment]
Nah you got it right. I had actually hoped to get those removals into 7.1, but realized it'd be better to give it a version since somewhat formally announcing their depreciation so people could have a chance to update their codebases. You reminded me I still need to put up a blog post or something announcing the list of deprecations.

**Comment by neeharv** [comment]
@developit Is there a formal deprecation policy for Preact, in terms of outputting warnings? That could help. Also a tiny codemod to do this conversion?

**Comment by developit** [comment]
There are no warnings because we can't afford the overhead, but I have put together a document of the likely breaking changes in Preact 8.  Each change includes a polyfill you can drop in to make it work like 7.x, and an explanation of how to update.  I'd love to put together codemods though.

Here's the document:
https://gist.github.com/developit/89e0e6decb8fb5eb00def024b6fb7bd7

**Comment by developit** [comment]
`componentDidUmount()` is gone in 8.0.

**Comment by povrazor** [comment]
You will be missed `comonentDidUnmount()` :ghost:
