### ISSUE TITLE
List of Goals and Non-goals would be very helpful

### ISSUE THREAD

**Issue by xaduha** [developit/preact#30]
A commitment like that from a developer would make it easier for people to "invest" in the framework, they would know what to expect in the future.

**Comment by developit** [comment]
@xaduha awesome idea, I will get this added to the wiki.

**Comment by n4gashi** [comment]
I am pretty interested into this too, because I can see the benefits that you are bringing to us, by using a smaller library with the same core goal as react, but I just want to be sure that : 

- reasons of using preact are because of the smaller filesize and it's focus on components (react is only in 0.x, so I know all of this can be adopted in 1.x, there is so much optimizations to come)
- preact will not defer in the way react are adopting things, because for now react has a so big community that if you tend to defer in another way, I'm not sure it would be worth it for me using preact. Sad to say but only the libraries with huge communities are making it.

Hope to hear from you soon on what's your goals are !

**Comment by developit** [comment]
@n4gashi Yup, I will make sure to cover those points.  That's the reason I created [preact-compat](https://git.io/preact-compat), so that there is a way to move between preact and react freely, or mix and match within a single project.  It's important to me that people have the freedom to use what fits their needs, and a project's needs can change over time. Cheers.

**Comment by developit** [comment]
The list is now available on the Wiki, please check it out make any suggestions you have!
https://github.com/developit/preact/wiki/Project-Goals
