### ISSUE TITLE
Click on Checkbox Fires Twice

### ISSUE THREAD

**Issue by pahund** [developit/preact#358]
I have a checkbox with an onchange handler like this:

![index_js_-_private-messages_-____git_private-messages_](https://cloud.githubusercontent.com/assets/1639313/19351122/c2092536-915a-11e6-9eac-f58a868e2f90.png)

When I click the checkbox, nothing happens. I think this is because the click triggers both a click and onchange event, one ticks the checkbox, the other unchecks it again (using Redux to handle the event).

![developer_tools_-_eingang_-_pahund_-_private_nachrichten_-_motor-talk_de_-_http___localhost_3000_](https://cloud.githubusercontent.com/assets/1639313/19351214/1ee64504-915b-11e6-9c59-c3906e7ef48d.png)

I'm using Preact 6.3.0 with Preact-Compat 3.7.1.

Is this a bug, or do I have to change my implementation when using Preact instead of React? It works without a problem with Facebook's React.

**Comment by developit** [comment]
I'd need to know roughly what `onChange` is doing in order to diagnose.  Click/change normalization is in preact-compat ([here](https://github.com/developit/preact-compat/blob/master/src/index.js#L321-L328)), so this issue might be better-suited to that repo.

I think you might be right though - it seems like the above linked normalization never removes the old `onchange` prop, so perhaps that's causing it to fire twice.

**Comment by pahund** [comment]
Should I move the issue to *preact-compat*?

In my app, when you click on a checkbox, a redux action is dispatched, which causes the state of the app to be changed, thus setting the checked prop of my Checkbox component.

**Comment by pahund** [comment]
Using *onClick* instead of *onChange* fixed the problem for me:
![checkbox_index_js_-_private-messages_-____git_private-messages_](https://cloud.githubusercontent.com/assets/1639313/19353057/733fc7cc-9162-11e6-9e14-95a1efdcba1c.png)

**Comment by developit** [comment]
Perfect, sounds like we just need to have preact-compat delete the `onChange` prop when it aliases it as `onClick`.

**Comment by pahund** [comment]
Glad to help, keep up the good work!

**Comment by developit** [comment]
This has been fixed in `preact-compat`, and will be released shortly.

**Comment by cedmax** [comment]
Hi, sorry to bother you on a closed issue, but I think the change you introduced broke the input[type="radio"]: looking at the code it seems like you are deleting the onChange for any input type not checkbox, in favour of an onInput, but the radio wouldn't work with it. 

Sorry if I'm wrong, I've been trying to debug this issue since a while in my app and I'm a little tired :D
