### ISSUE TITLE
Compatibility with tomchentw/react-google-maps (and more generally)

### ISSUE THREAD

**Issue by eightyfive** [developit/preact#385]
Hi,

I was wondering what's the compatibility level like. I am using `preact-compat` and was expecting a drop-in compatibility.

But it doesn't seem to be the case. For example https://github.com/tomchentw/react-google-maps doesn't work with preact.

I'm using the following versions:
```
    "preact": "^6.4.0",
    "preact-compat": "^3.9.0",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "webpack": "^1.13.3",
```

So I like the idea of getting a huge file decrease for free, but is it for free?

I hope I don't sound judgmental, I obviously respect (a lot) the work put into such a library.

Cheers,
Ben

**Comment by developit** [comment]
Hi Ben,

The way third party libraries use React varies incredibly widely. The only specific compatibility issue I'm aware of right now might affect this library, which is that Preact recycles nodes too aggressively - some react components add new non-react elements to the DOM and expect them to remain there despite future diffs. This is a design I had hoped to avoid copying in preact, but it's turned out to be a nuisance in a few cases (react-virtualized is another such case).

The design of preact-compat is drop-in, and you'll find 95-99% of code works out of the box, but there are still a few "long-tail" intricacies being smoothed out. Those are bugs, but since there are thousands of react libraries out there, it's an ongoing process. I think we are nearing the end of it, because fewer and fewer issues seem to be coming up, but there are still a few left to be addressed such as this. 

So - long story short, you're hitting what is now considered to be a preact-compat bug (lack of compatibility), but its one I want to fix by changing how preact itself works. Thst takes a little more time and planning, which is underway now.

**Comment by eightyfive** [comment]
Hi,

Thank you. Feel free to close this issue and if so, is there another related issue I can follow?

**Comment by developit** [comment]
Main one is here:
https://github.com/developit/preact-compat/issues/228

**Comment by developit** [comment]
This should be fixed in version 7, which you can install via `npm i -S preact@beta`.

**Comment by developit** [comment]
Closing as this is fixed in 7. Feel free to re-open if you think I'm crazy! 👍

**Comment by vibhash1083** [comment]
fitbounds of react-google-maps doesn't work with preact.
