### ISSUE TITLE
Travis leaking env variables

### ISSUE THREAD

**Issue by mkautzmann** [developit/preact#387]
While researching for #386 I've found out that Travis is leaking the SAUCE_USERNAME and SAUCE_ACCESS_KEY environment variables.

I figure you don't want to share the access key. So I recommend you to change the access key and follow [this guide](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) to secure it.

**Comment by developit** [comment]
It was actually previously obscured as per that article, but it meant Pull Requests failed to connect to saucelabs. I'm thinking maybe we turn off saucelabs entirely for PRs though.

**Comment by mkautzmann** [comment]
If I'm not mistaken it is already off for PRs. I'm talking about the Travis build page, where it shows the env variables in the log.

See the below screenshot:
![travis_preact_screen](https://cloud.githubusercontent.com/assets/1051644/20025814/6839dcd6-a2d9-11e6-8ca5-23e2bb0925f9.jpg)


The article I linked contains a way to secure the env variables in Travis.

**Comment by developit** [comment]
In the article you linked, it says "Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.".  This is what I ran into, and why I disabled the securing technique.

I think the best thing would be to re-enable the obscured access_key, and turn off saucelabs-based testing for PRs.  This would still leave phantomjs tests running, and perhaps then it'd be reasonable to look into running chrome/firefox headless tests in addition to saucelabs.

**Comment by mkautzmann** [comment]
You are right, the way Travis CI handles env variables makes it hard to use them safely on PRs.

I got confused, I was focusing on commits/merges to master because the following line should already be blocking Sauce when testing PRs (assuming TRAVIS_PULL_REQUEST is passed correctly by Travis): https://github.com/developit/preact/blob/master/test/karma.conf.js#L4

In reality it is not, as we can see from [Travis' logs](https://travis-ci.org/developit/preact/builds/173047962).

I agree that Sauce should not execute on PRs, we can use secure env variables and test with Sauce only on commits to master.

**Comment by robertknight** [comment]
Enable Sauce labs for PRs was something I suggested after my devtools PR broke the tests for IE.

I assume that we're using a Sauce Labs open source account for Preact? In that case, is it really a problem if the account key is exposed to PRs?

**Comment by developit** [comment]
Not a huge problem for me since the account is pretty limited and anyone can sign up for OpenSauce for free, but I think when combined with the flakey IE and mobile tests it might just be too annoying.  I've had to turn down GreenKeeper because the PRs would randomly fail due to SauceLabs, and that means everyone gets notification spam when the PR should just have be green.

**Comment by mkautzmann** [comment]
OK, but why PRs are being tested with Sauce Labs when [test/karma.conf.js](https://github.com/developit/preact/blob/master/test/karma.conf.js#L4) seems to check for TRAVIS_PULL_REQUEST.

Is the TRAVIS_PULL_REQUEST env variable disabled in Travis? Am I missing something in the code?

If it is something disabled in Travis, that was what caused my confusion about this issue.

**Comment by developit** [comment]
I had done that but wasn't able to get it working for some reason (strange). If it worked, thst would do what we want: run karma tests in phantomjs for PRs and SauceLabs for merges.

**Comment by developit** [comment]
If you see anything that might have caused that I'd be super open to a PR, haha.

**Comment by developit** [comment]
Fixed thanks to your excellent PR, and I've now re-hidden the sauce access key in Travis.

**Comment by mkautzmann** [comment]
Great! So I'm closing the issue.
