### ISSUE TITLE
Inputs pre-filled with old values

### ISSUE THREAD

**Issue by matthewmueller** [developit/preact#389]
I'm not sure if this is a bug or my mistake, but I'm getting inputs pre-filled with old information (ex. dashboard input has username pre-filled from a signup page)

I've added keys to each of the top-level pages:

```js
div.key('Login')(
  input.type('text')()
)
```

```js
div.key('Dashboard')(
  input.type('text')()
)
```

I am able to fix this by adding keys directly to the inputs, but this makes me worry that other things aren't properly being diffed. Do parent keys apply to children in the tree as well?

**Comment by developit** [comment]
Hmm - I'm thinking you're getting a full diff because the old keyed root gets immediately recycled as the new one. Adding a keyed component to the tree would likely fix that. 

Also the input value issue is because preact doesn't constrain DOM properties it hasn't been used to set - that means adding a value property to the inputs would reset their state when they get recycled across pages.

**Comment by matthewmueller** [comment]
ahh got it! so the proper approach would probably be to always use controlled inputs with a value
