### ISSUE TITLE
flatten children in preact.h(...)?

### ISSUE THREAD

**Issue by matthewmueller** [developit/preact#406]
Any interest in flattening the children in `preact.h(...)` ?

This would allow your plugins to return arrays of children, which can be useful for things like meta tags:

```js
<head>
   <title>Hello world!</title>
   <Metas site={props.site} />
</head>
```

**Comment by developit** [comment]
Hmm - `h()` does flatten children ([here](https://github.com/developit/preact/blob/master/src/h.js#L27-L30)). Returning an Array from a component (pure functional or otherwise) isn't currently possible because the render path is 1:1 dom<->vdom. Some bits that limit that are [resolving nested PFC's](https://github.com/developit/preact/blob/master/src/vdom/component.js#L108-L110) and the various parts of the codebase that expect rendering a component to produce a DOM node (whereas it would then be producing an Array of them).

I'd love to support this, I just have no idea how to do it without doubling the size of the lib. In the back of my mind I'm thinking clever use of DocumentFragments, but I haven't tried that out at all. They are a little weird post-insertion.

**Comment by thysultan** [comment]
if the component returns an array you could create a fragment VNode that has a unique signature(i.e `{type: 11, props: {}, children: [...returned array]}`) passing the array as its children. then use createDocumentFragment instead of createElement when you come across an element with this signature.

**Comment by leeoniya** [comment]
@developit @thysultan 

I think the problem is not simply flattening, but actually recognizing fragment boundaries during DOM reconciliation. I explored doing this recently in domvm [1] which also has a 1:1 vdom to dom mapping. domvm supports template flattening but not fragment components. @trueadm also made an interesting experiment for using a single comment or empty textnode placeholder to represent a fragment position but it still suffers from the following:

The main issue is fragments-within-fragments and this isnt something createDocumentFragment can solve because while they can serve as temporary containers in place of a root dom node, they get emptied once you use an `appendChild` them into the real dom, so become useless afterwards.

There are other issues which impact performance as well, such as moving a fragment (contiguous block of elements) into the correct position. The dom has no cheap way of moving multiple childNodes at once, so even with an optimal algo that detemines the exact new location of the fragment, you're stuck with at least a children-number of insertBefore ops.

It's possible to support fragments without too mch issue as long as you can swallow the dom reconciliation cost. But it comes with the caveat that you cannot have nested fragments without severly increasing reconciliation complexity.

I've put it on the backburner [3] for now in the interest fo getting v2 out the door, but it'd be interesting to explore/discuss some options. Take a a look through the referenced threads if curious.

[1] https://github.com/leeoniya/domvm/issues/101#issuecomment-260077907
[2] https://github.com/trueadm/fragment-node/issues/1
[3] https://github.com/leeoniya/domvm/tree/defineFragment

**Comment by matthewmueller** [comment]
Ahh thanks the info @leeoniya! Sounds like it's not worth the cost. Going to close this one. Thanks guys!

**Comment by developit** [comment]
Wow that was an awesome explanation @leeoniya. Thanks a bunch!
