### ISSUE TITLE
How does preact compare to react-lite?

### ISSUE THREAD

**Issue by andyhu** [developit/preact#44]
https://github.com/Lucifier129/react-lite

**Comment by developit** [comment]
@andyhu I should clarify up-front: Preact is not just an attempt to perfectly emulate React's behavior in a small library size (although `preact-compat` probably _is_ that attempt).  It is an implementation of the concepts of React, but it is not free of opinions.  There is a fairly complete list of [differences between Preact and React](https://github.com/developit/preact/wiki/Differences-to-React) on the wiki.

Here are some key differences:

## Preact is faster

[This standard benchmark](https://localvoid.github.io/uibench/) shows Preact is more than 2x faster overall:

<img width="541" src="https://cloud.githubusercontent.com/assets/105127/12891869/801fe496-ce57-11e5-8770-b03286f75b0d.png">

## Preact is much smaller

Preact is 3.5Kb, react-lite is 17kb.

## More Features

Preact actually has more features from React than react-lite does!  It can render to a static HTML string via [`preact-render-to-string`](https://git.io/preact-render-to-string). Further, Preact supports isomorphic rendering, meaning your code on the client picks up where the server rendered markup leaves off - the first render on the client is a diff, instead of a replace. Also, instead of being a no-op as they are in react-lite, `PropTypes` are fully supported (ie, respected/validated) in `preact-compat`.

## Preact is Modern

Preact is written in ES2015. It intentionally avoids bringing deprecated APIs into its core, instead leaving that work to `preact-compat` so that it is entirely optional.  It is pluggable via `vnode` hooks, includes performance features like batching right out of the box, and works in IE9.

**Comment by developit** [comment]
Closing since this is answered. Please let me know if I missed anything important.
