### ISSUE TITLE
Webworkers

### ISSUE THREAD

**Issue by blainekasten** [developit/preact#448]
There has been a lot of discussion and controversy around using webworkers for diffing logic in React. There are obvious benefits of moving this computation off of the main thread. (This article highlighting that https://aerotwist.com/blog/when-everything-is-important-nothing-is/)

I'm curious if you've though about using webworkers at all for vdom diffing.

**Comment by developit** [comment]
Hi @blainekasten! Someone actually opened an issue for this already: #417

I spent all last weekend building a demo of a fully Workerized Preact app, and have come to the conclusion that Web Workers are not particularly well-suited to VDOM diffing.  They are much better used for tasks with higher complexity and lower input/output size.

There are a bunch more details in #417 that I think you'll find interesting, including some tweets where I showed the effects. I'll close this out since it's a duplicate, but definitely check out that thread if you're interested.
