### ISSUE TITLE
How to install PReact?

### ISSUE THREAD

**Issue by budarin** [developit/preact#449]
How to install PReact?
where novice have to found info about installation and confiration PReact ?

**Comment by developit** [comment]
You need to install it via npm. Here are their instructions for Preact:
https://www.npmjs.com/package/preact/tutorial

That said, I strongly recommend starting with a boilerplate if you're new to all this stuff. 
Preact's is called [preact-boilerplate](https://github.com/developit/preact-boilerplate), and it will get you up and running in around 5 minutes :)

**Comment by budarin** [comment]
I'm sorry, but its litlle bit unclear - I came to the site where is documentation but not find any word about installation process

**Comment by developit** [comment]
It's the same as any frontend library, you can get it from npm:

```
npm install preact
```

That said, in order to better explain how to get started, I'd need to know where you're coming from: are you wanting to use Preact in a script tag on a web page, or do you have some sort of build tool setup you're using already?

Cheers!
