### ISSUE TITLE
Questions/confusion about Preact

### ISSUE THREAD

**Issue by GRardB** [developit/preact#533]
Hey!

I'm rewriting an Ember project of mine in "React," and _one_ of my many reasons for doing so is that Ember doesn't lend itself well to small JS bundles. I decided to give Preact or Inferno a shot, and since `inferno-compat` is sort of a misnomer (it doesn't include `Component`, which leads to third-party libraries breaking), Preact is the default winner! I took my React project and turned it into a Preact project, and everything works.

However, I'm a little confused...

In the Inferno repo, they list the differences between Preact and Infero, and one of the things they say is:

>Inferno is much faster than Preact in rendering, updating and removing elements from the DOM. *Inferno diffs against virtual DOM, rather than the real DOM* (except for when loading from server-side rendered content) which means it can make drastic improvements. *Unfortunately, diffing against the real DOM has a 30-40% overhead cost in operations.*

This seems to imply that Preact diffs agains the real DOM, rather than a virtual DOM. Is this true? I can't seem to find anything online that supports this claim.

If it _is_ the case, it looks like it's at least possible to "turn on" the usage of a virtual DOM in Preact or something? In the Preact README, it says:

>Out of the box, Preact provides an h() function that turns your JSX into Virtual DOM elements (here's how). It also provides a render() function that creates a DOM tree from that Virtual DOM.

What does this mean, exactly? Is this for building my own virtual DOM, for my own use? Does it mean that there's no virtual DOM by default unless I include `h()`?  Do I need to import `h` as well? Does it matter that I'm using `preact-compat`?

I'm new to Preact, but not to React, and none of this seems super clear to me 😕 

Sorry for the long question! Hopefully, it's easy enough to explain so that an answer requires less typing.

Thanks!

**Comment by mkxml** [comment]
I'm no Preact guru 😄 , but I'm using it too and I'll try to briefly explain some points.

1) Preact does implement the VDOM concept like React, node changes are compared in VDOM before applying final patches to the DOM. The implementation is done differently from Inferno, though. @developit may provide further details.

2) `h()` and `render()` are like `React.createElement` and `ReactDOM.render` for Preact. You may not see `h()` much because most files are written in JSX and later compiled to use the `h` function. Tools like babel and webpack can hide the use of `h` in your files completely so that it becomes totally implicit.

3) There is no usual way to skip VDOM usage in Preact, VDOM is mandatory. You need `h()` to create components and elements in Preact, it automatically creates a VNode for you.

4) `render()` grabs the VNode tree (elements/components created with `h`) and renders it in the real DOM.

5) If you use `preact-compat` you will add some extra code to your bundle but then Preact will work just like React in most cases. Most of `React`'s functions and properties, like `createElement` which maps to `h`, become available. `preact-compat` adapts and disguises Preact so that devs have an easy drop-in replacement for React. I would recommend you to stick to the core if possible, if you plan to use a lot of React dependent libs then `preact-compat` may be worth it.

**Comment by Download** [comment]
When you implement render, you are returning VDom nodes, in all three systems.

Tip: Assign your VDom tree to a variable and log it to the console before returning it, to get a better idea:

```js
function MyComponent(props) {
  var vdom = (
    <div>
        <b>Hello, {props.message}</b>
    </div>
  )
  console.info(vdom);
  return vdom;
}
```

The difference happens afterwards. Both React and Inferno keep an old copy of the most currently rendered VDom tree in memory, so they can diff the newly rendered tree against the old one. Preact has taken a different route. It does not keep an old copy around for diffing. Instead, it diffs the new VDom tree against the *real DOM*.

I think Jason explained it in some blog post when introducing Preact. He had done some testing and concluded that, as long as you don't actually *change* anything, the real DOM is quick enough to do diffing against. Presumably he wanted to save bytes. There is a reason Inferno is nearly 3 times as big as Preact...

So the performance question becomes: which is more important to you: TTI (time to interactive) or frame rate?

If you are doing very complex stuff at high frame rate, inferno may help you. If not, probably Preact is better.

**Comment by GRardB** [comment]
Perfect! Thanks for taking the time out to help, guys! All of that makes sense.

I think in my case, I won't be doing complex changes to the DOM, so I should be okay :grin: :+1:

**Comment by developit** [comment]
All good explanations, thanks for fleshing this out :)

@GRardB It's actually a little less different than it seems - Preact does diff VDOM against DOM, but it caches things on DOM nodes rather than actually diffing against the nodes themselves.  In reality, that ends up working a whole lot like VDOM <-> VDOM diffing, just Preact doesn't need to keep the old VDOM tree around to diff against.
