### ISSUE TITLE
Allow rendering in alternative (not browser) DOM implementation.

### ISSUE THREAD

**Issue by majo44** [developit/preact#567]
I know that there is a preact-render-to -string project, but it have some limitations with accessing to real dom/document/window ect. from component, also async rendering is not trivial. 
There are few implementations of DOM for node.js eg [domino](https://github.com/fgnass/domino).
This will be very useful to have possibility to render directly to such implementations instead of render to string.

The required change is only to remove reference to global _document_ object and replace it by using _parent.ownerDocument_. I saw there is only one on two places (_createNode_) in code which are using global _document_ object.  This should be very trivial work. 

After such change there should be possibility to :

```
import * as domino from domino;
import { h, render} from 'preact';

var window = domino.createWindow();
var document = window.document;

render((
    <div id="foo">
        <span>Hello, world!</span>
        <button onClick={ e => alert("hi!") }>Click Me</button>
    </div>
), document.body);
```

Best Regards.

**Comment by developit** [comment]
@majo44 this is probably not possible given the filesize constraints of Preact.  Your demo works if you polyfill though:

```js
import * as domino from domino;
import { h, render} from 'preact';

Object.assign(global, domino.createWindow());

render((
    <div id="foo">
        <span>Hello, world!</span>
        <button onClick={ e => alert("hi!") }>Click Me</button>
    </div>
), document.body);
```

**Comment by majo44** [comment]
I know that I'm able to expose document/window to global but on node I want to have separated _document_ for each separated request. Render is always in context of some element so there should not be a problem to take the _ownerDocument_.

I made some PR https://github.com/majo44/preact/pull/1/files and this works for me fine.
But there is one hacky think https://github.com/majo44/preact/pull/1/files#diff-a0896fa5d65b1d80ca4d496badbae50fR47 

Unfortunately I do not know how to provide _document_ to component rendering. So I made assumption that rendering is synchronous that is why this solution works. 

As you see there is not a lot of changes, and this is not any braking change, all test are pass.

**Comment by developit** [comment]
The synchronous assumption ends up removing any difference between the two approaches.  It's also slower to lookup ownerDocument than to use a document global.

What's the reasoning behind wanting a separate document for every request?  That seems like unnecessary overhead, since the only thing Preact uses `document` for is `createElement`, which is pure.  Preact is a singleton - any attempts to change that are likely futile, its part of the design and one of the reasons the library manages to be so small.

**Comment by majo44** [comment]
As I said, this is not perfect solution, in fact this is just workaround, I'm not very familiar with preact src.
But this is different then global document. (If my assumption is fine) The globalDoc variable will be proper in each separated render cycle. 

eg. this example should works fine even with this workaround, even for multiple simultaneous requests
```
import * as domino from domino;
import { h, render} from 'preact';

function sendJSX(jsx, res, res) {
         let doc = domino.createDocument();
         doc.querySelector('header').append(.... // eg. some direct dom work
         fs.readFile( ....   //eg. some async work
         render(jsx, doc.body);
         fs.readFile( ....   //eg.  some async work
         doc.querySelector('header').append(.... // eg. some direct dom work
         res.send('<!DOCTYPE html>\n' + doc.innerHTML);
}

app.use((req, res, next) => {
    res.sendJSX = jsx => sendJSX(jsx, req, res)
    next();
})

app.get('/index', (req, res) => {
    req.sendJSX(<div>Hello word !</div>);
})
```

I think this example is good showing why to separate `document` for each request.
BTW. [google/incremental-dom](https://github.com/google/incremental-dom) is using very similar approach https://github.com/google/incremental-dom/blob/51afdd86970b28dcb74a76461770f84ad280326e/src/core.js#L85

I do not, know, maybe there will be some impact on performance, but if, this will be very very very lite. 
I made js-repaint-perfs , and I can't see any impact. 
But on other hand I think it is better to have smaller list of depended apis then wider. 

The impact on lib size is almost 0, just few bytes.

**Comment by majo44** [comment]
Ok I'm a bit distracted, I can do this without preact changes.
```
...
function sendJSX(jsx, res, res) {
         let doc = domino.createDocument();
         doc.querySelector('header').append(.... // eg. some direct dom work
         fs.readFile( ....   //eg. some async work
         global.document = doc;
         render(jsx, doc.body);
         delete global.document;
         fs.readFile( ....   //eg.  some async work
         doc.querySelector('header').append(.... // eg. some direct dom work
         res.send('<!DOCTYPE html>\n' + doc.innerHTML);
}
...
```

This is still ugly, but works. 
So is up to you to simplify this on lib level :)
Best regards.

**Comment by developit** [comment]
I still don't think this is something Preact will ever account for. It does not store or rely on *any* global state in the document, so there is absolutely no difference between passing `render()` a new document each time, or letting it share one.  Furthermore, Preact (currently) recycles DOM elements - this would mean it is reusing DOM elements from one `domino` instance inside another `domino` instance - probably not something you want, and unlikely something `domino` properly accounts for (unless you're calling `document.importNode`, but even then..

I don't intend to pursue overriding the document global, and I think I've given fairly good justification for taking that position.  Preact is a singleton by design, passing in a `document` reference doesn't change anything about that. All it does is increase complexity in order to superficially support a use-case, without actually doing so.  Think about the real implications of this:  caching/recycling, creation, removal, etc - all of these must then take into account the fact that the document is not a global.

BTW - why do you need to use `document.querySelector()` in the first place?  Just pass a new root element and query within that:

```js
import domino from 'domino';
global.document = domino.createDocument();

function sendJSX(jsx, req, res) {
    // fresh DOM tree every time, with no locking issues:
    let root = document.createElement('root');

    root.querySelector('header').append(.... // eg. some direct dom work
    fs.readFile( ....   //eg. some async work
    render(jsx, root);
    fs.readFile( ....   //eg.  some async work
    root.querySelector('header').append(.... // eg. some direct dom work
    res.send('<!DOCTYPE html>\n' + root.innerHTML);
}
```

**Comment by majo44** [comment]
Ok I found better workaround.
I'm able to do this by the thread local storage (eg. Zone.js)

```
// exposing window from current zone
Object.defineProperty(global, 'window', {
    get: () => {
        return Zone.current.get('window');
    }
});

// exposing document from current zone
Object.defineProperty(global, 'document', {
    get: () => {
        return Zone.current.get('document');
    }
});

// this fn creates Zone, and expose the doc and win on it
function runInDomZone<T>(fn: () => T): T {
    let window = domino.createWindow(' ');
    let document: any = window.document;
    document.ownerDocument = document;
    return Zone.current.fork({
        name: 'DOMZone',
        properties: {
            window: window,
            document: document
        }
    }).run<T>(fn);
}

// middleware 
// on express each request can go thought Zone 
app.use((req, res, next) => {
     runInDomZone(next);
})

// req handler
app.get((req, res) => {
    // it is global document, but it is taken from Zone
    document.querySelector('header').append(.... // eg. some direct dom work
    fs.readFile( ....   //eg. some async work
    render(jsx, document.body);
    fs.readFile( ....   //eg.  some async work
    document.querySelector('header').append(.... // eg. some direct dom work
    res.send('<!DOCTYPE html>\n' + document.innerHTML);
});

```
Regards.
