### ISSUE TITLE
Remove/rewrite documentation for linkState()

### ISSUE THREAD

**Issue by IrregularShed** [developit/preact#638]
The README and website still talk about the decoupled `linkState()` as being part of the project. I'm not sure what's best - remove the references all together or nudge visitors over to the new project?

**Comment by developit** [comment]
We can remove it from the README and just drop a link in its place.  I think it makes sense to keep the Linked State section of the website around and just update it to reflect the independent module.  I'm hoping to put together a better menu structure (and information architecture in general) for the site so that we can accommodate more guides and tutorials, which would be where the Linked State page should end up.

**Comment by IrregularShed** [comment]
Legend 😀

**Comment by sxcooler** [comment]
Although you have removed linkState from preact it self, it still in preact.d.ts:
![image](https://cloud.githubusercontent.com/assets/3192045/25077212/41da056e-235a-11e7-9390-6072265c8757.png)
plz synchronize the change...

**Comment by developit** [comment]
Happy to accept a PR!

**Comment by TheNeikos** [comment]
There is also the wiki page: https://github.com/developit/preact/wiki/Linked-State

Maybe this would be best to just link to: https://preactjs.com/guide/linked-state
