### ISSUE TITLE
componentDidMount fires before child component is attached to DOM

### ISSUE THREAD

**Issue by unindented** [developit/preact#65]
I have an easy repro here: http://jsfiddle.net/pvbvj23o/

**Comment by developit** [comment]
Interesting. Debugger shows it's attached to the parentNode from `<App>`, but `<App>` hasn't yet been appended to the DOM itself.  I'd love to avoid deferring `componentDidMount()`, since that would cost a traversal during render, but that might be the only way.  Are you sure React only calls this hook once the whole tree is mounted?

**Comment by unindented** [comment]
Looks like React only calls the hook once the element is mounted: https://jsfiddle.net/x6xpdkjL/

The docs seem to confirm: https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount

**Comment by developit** [comment]
Awesome, thanks for investigating. I'll try to look into this tonight.

**Comment by c2h5oh** [comment]
Still present in 4.5.

**Comment by developit** [comment]
Yup, on my to-do list. thx.

**Comment by developit** [comment]
Hooray!! 👏 🎉 🍻

**Comment by developit** [comment]
Released in `5.2.0-beta.0`.
