### ISSUE TITLE
simple cli for "bundling without bs"?

### ISSUE THREAD

**Issue by Pomax** [developit/preact#721]
Every time I'm working on a (p)react PoC codebase, I wish there was a CLI that just allowed me to say `CLItoolname entryfile outputfile` and not bother with any of the webpack, babel, etc. cruft that is completely irrelevant to build a bog standard bit of "it uses ES6, it uses JSX, it needs to become something I can load in the browser". 

Would it make sense to offer a CLI tool with preact that achieves that? And if it needs to install babel, webpack, etc. as part of its dependency tree, that's cool, but there is nothing about those things I should have to configure if I just want to compile the kind of code that the README.md shows.

(Note that this is drastically different from a "preact-start-project" or the like: I just need to write some quick PoC code, with a tool that'll bundle that PoC code, so I'm not looking for full framework-based project bootstrappers)

**Comment by viankakrisna** [comment]
It sounds like https://github.com/insin/nwb#quick-development :)

**Comment by developit** [comment]
Hi there - we released preact-cli for exactly this reason! It's a one-command, one-dependency bundling tool that bakes in all the best practises and produces awesome code-splitted bundles with no configuration at all.

Here the entire project setup process:

```sh
# Install it (once and you're good):
npm i -g preact-cli

# create a new project:
preact create my-great-app
cd my-great-app

# start a live-reload (HMR) dev server:
npm start

# go to production:
npm run build
```

**Comment by developit** [comment]
FWIW I only just realised we never even added a link to Preact CLI in the Preact readme - really need to, haha.

**Comment by Pomax** [comment]
@developit  =D

**Comment by robertknight** [comment]
As noted above, the preact-cli project resolves this and it is now prominently mentioned in the project's README.

**Comment by oren** [comment]
@robertknight shouldn't the [getting started](https://preactjs.com/guide/getting-started) also mentioned the CLI?

**Comment by developit** [comment]
Yes - I [updated the readme](https://github.com/developit/preact/commit/d213b086e36e0ec3c4700d36a5e6a3368af74894), and we could effect those changes on the website too.

**Comment by developit** [comment]
Regarding `npx`, that looks nice!  `preact-cli` does need to be global though, since you run `preact create <name>` to initialize a new project and it does all the setup for you.  It installs itself as a local devDependency of the project and that gets used for all the building and whatnot, but in order for `preact create` to work it'll need to be global \*

_\* or in the parent directory of the place you're creating a project, but that's sortof the same as a global._

FWIW I use this bash alias to run stuff out of node_modules so preact-cli and gzip-size-cli are kinda the only tools I have installed globally:

```sh
# npm-exec webpack -p
alias npm-exec='PATH=$(npm bin):$PATH'
```
