### ISSUE TITLE
Using class names

### ISSUE THREAD

**Issue by jrock2004** [developit/preact#729]
So in a component I added an image and to it I added a class name. I have tried class="" and className="". Am I doing something wrong? Is it because I should make the site logo another component?

![image](https://user-images.githubusercontent.com/655716/27059359-0d9cd38c-4fa4-11e7-8eb2-75eb2cfcd5c1.png)

**Comment by developit** [comment]
[CSS Modules](https://github.com/webpack-contrib/css-loader#modules) is enabled within `src/components`, which means when you import `./style`, you're actually getting back an Object mapping of local-to-generated classNames:

```js
import style from './style';
console.log(style);
// {
//   header: 'header__2g09h',
//   'menu-button': 'menu-button__2g09h',
//   'site-icon': 'site-icon__2g09h',
//}
```

This means you need to use those object keys instead of string literals for class/className.  In your screenshot this was already being done for `activeClassName={style.active}`.

```js
<img class={style['site-icon']} src="/assets/icons/icon-128x128.png" />
```

With this in place, running your code will produce an image that looks like:

```html
<img class="site-icon__24g09" src="/assets/icons/icon-128x128.png">
```

---

Let me know if that makes sense :)

**Comment by jrock2004** [comment]
I do. But I am curious to why does it work this way for header\

`<header class={style.header}>`
