### ISSUE TITLE
element not removed when re-rendered to a different one with a component

### ISSUE THREAD

**Issue by kruczy** [developit/preact#73]
Hey,
 I found that when re-rendering an element to a different one wrapped in a component the original one stays in the dom. 

example: http://jsfiddle.net/nu7Lucfj/

this happens for any element that has a different name than the one put in directly

if you change the span to a div it works fine

**Comment by developit** [comment]
Hmm - interesting case here.  The semantics of that third argument to `render()` are currently "existing rendered version to update in-place", which is why it doesn't remove the mismatched node.  This might be something we need to do a poll about.  Good find!

**Comment by kruczy** [comment]
it actually works fine if the span is not wrapped in a component: http://jsfiddle.net/ext7nm02/1/

**Comment by developit** [comment]
Ahh, good hunting - I think that means we can call this a bug :)

**Comment by developit** [comment]
Was bit by this today when building [preact-portal](https://github.com/developit/preact-portal).

**Comment by developit** [comment]
I believe I have discovered the issue. Preact's diff algorithm tries very hard to retain all state in locals rather than relying on things like Array.prototype.length (for performance).  When a keyed `VNode` is determined to be unused during diff, it gets appended to a list of children that are reclaimed at the end of the diff.  However, there was a conditional around the reclamation to avoid operating on empty sparse Arrays, and one of the values was not being updated to reflect newly orphaned keyed VNodes.

In the screenshot below (from @andrewn's Codepen repro), the value of `childrenLen` is correctly updated to be `1` (one orphaned VNode), however, the value of `min` is left unmodified after diffing, which means it remains as `1`. This meant Preact was skipping removal of the VNode entirely.

<img width="574" alt="screen shot 2016-03-09 at 10 49 42 am" src="https://cloud.githubusercontent.com/assets/105127/13641064/260d702c-e5e5-11e5-8a8d-7a116782df67.png">

I'll get a fix in right away, but I want more tests around keys in order to cover edge cases like this.

Thanks to both of you for your help!

**Comment by developit** [comment]
@kruczy Thanks again for your repro. I just released [4.1.2](https://github.com/developit/preact/releases/tag/4.1.2), and have included your JSFiddle as [a new test].

Here is your repro running against Preact `4.1.2` showing the intended behavior: [JSFiddle](http://jsfiddle.net/developit/nu7Lucfj/1/).

[a new test]: https://github.com/developit/preact/blob/master/test/browser/render.js#L500-L518

**Comment by kruczy** [comment]
Great :+1:  Thanks!
