### ISSUE TITLE
Extending Component - example, not working, why?

### ISSUE THREAD

**Issue by jobsboris27** [developit/preact#81]
When I tried to use your example, I got error - this[i].bind is not a function.
Why?

https://jsfiddle.net/cty6ybrq/4/

**Comment by developit** [comment]
@jobsboris27: ah, sorry, that is an older example and I moved it into the wiki without checking if it had been broken. The error is because it's not checking if `this[i]` is actually a function before calling `.bind()` on it, so it's trying to bind things like `this.state`, which is an object. 

Will update the demo.

**Comment by jobsboris27** [comment]
@developit thanks!

**Comment by developit** [comment]
@jobsboris27 The issue was due to Babel correcting it's behavior to match the ES6 spec: class methods are non-enumerable, which makes it impossible to auto-bind them at runtime (since you can't list what methods a class has).

I've modified the example to use an explicit list:
https://jsfiddle.net/developit/cty6ybrq/5/
https://github.com/developit/preact/wiki/Extending-Component

Thanks for noticing this!
