### ISSUE TITLE
Rendering serialized trees

### ISSUE THREAD

**Issue by fab1an** [developit/preact#826]
I'm using preact in an electron-app. In electron the main-process and the rendering-process (= dom) are separate and communicated via json.

Right now I'm passing computing data in main and pass it to the render-process where preact will generate the tree and apply it to the DOM.

For simplicity, I would like to
1. do the preact-tree-building in the main-process
2. then serialize them to JSON
3. receive them in the browser-window and call `render()` to apply them to the DOM.

**Questions**
* Are h(..) trees serializable?
* Does preact perform worse if I pass the entire tree, where all components are resolved to their subtrees so that only html-elements are left, to `render()` every time?
* Does preact use keys or component-type to accelerate `render()`?

**Comment by g-harel** [comment]
This might not be relevant to your use case, but I imagine that even if it could serialize the tree, it would be very difficult to pass event handling functions like onClick through json.

**Comment by fab1an** [comment]
That can be done via central dispatch and a naming convention.

**Comment by developit** [comment]
h() trees (virtual dom trees) are serializable, except for references to components.

Your idea would work fine if there were no components in the rendered tree, since it would simply be nested objects of the form `{ nodeName: String, attributes: Object, children: [ ] }`.

For your questions:

- Partially, but not when Components are involved as their `nodeName` properties are constructor references
- Yes, quite significantly. This circumvents subtree rendering, one of the most important performance optimizations.
- Component type (nodeName) and `key` are mainly used to determine optimal reordering.

Regarding your use-case, I actually think you might be able to use the exact technique from my [Web Worker demo](https://github.com/developit/preact-worker-demo) here.  It runs `preact` and a Preact application in a dedicated worker (analogous to your Node process), rendering into a tiny 1kb fake DOM called [undom](https://github.com/developit/undom). Changes to that DOM structure are tracked using its MutationObserver implementation and sent to the page process via postMessage. The changes are applied asynchronously as CPU becomes available via requestIdleCallback.
The worker demo also adds in something you're bound to run into: proxying DOM events back into the dedicated worker process so your app can react to them.  It does this using event delegation, and it works quite well.  Certainly worth taking a look :)

**Comment by fab1an** [comment]
Perfect answer, thank you, that is exactly the kind of thing I was looking for.

**Comment by fab1an** [comment]
Will the mutation-observers be included in undom-master?

**Comment by developit** [comment]
No, it'll be done as a plugin. It's near the top of my todo list (finally!)
