### ISSUE TITLE
Child components become undefined in HOC after rerender component

### ISSUE THREAD

**Issue by vyshkov** [developit/preact#836]
Hi. I have a strange problem, which is not reproducing if i am using React.
I have such code:

```
const SomeComponet = props => (
    <div>{props.children}</div>
);

function connect(WrappedComponent) {
    return class Connect extends Component {
        componentDidMount() {
            setTimeout(() => this.forceUpdate(), 3000)
        }
        render() {
            console.log("children:", this.props.children)
            return <WrappedComponent {...this.props}/>;
        }
    };
}

const HOC = connect(SomeComponet);

export default () => (
    <HOC>
        <span>!!!!!!!!!</span>
    </HOC>
);
```

After this.forceUpdate() all props become empty, so in console i see such output:

> children: [VNode]
> children: undefined

And that span `<span>!!!!!!!!!</span>` is not rendering any more.

Please help me understand whats going wrong.

**Comment by pabla** [comment]
I have the same problem.

**Comment by developit** [comment]
This is because Babel transpiles `<a {...obj}>` to `h('a', obj)` without cloning `obj`.  Preact then [mutates the props passed to h() in-place](https://github.com/developit/preact/blob/master/src/h.js#L21), which is probably shouldn't be doing!  For now, passing any other prop to the child component will mitigate the effect, because it will trigger Babel to clone the props when expanding them onto the JSX element.

Here's a JSFiddle showing the fix (adding an "a" prop):
https://jsfiddle.net/developit/7utpc2gp/

**Comment by vyshkov** [comment]
Thank you @developit

**Comment by paranoidjk** [comment]
I think this is a bug of the babel. Since spread operator should do a shallow copy.

**Comment by marvinhagemeister** [comment]
Just tried the snippet in the original comment and I'm unable to reproduce the bug in  Preact X :tada:
