### ISSUE TITLE
Preact is constantly remounting subcomponents

### ISSUE THREAD

**Issue by youknowriad** [developit/preact#857]
While trying to migrate from React to preact, we noticed some mounting/rerendering issues;
Not sure if you consider this as a bug or not, but compared to react there's a difference in the way preact decides which component got dropped and which one got reordered when two siblings have the same type but not the same children.

Code examples are clearer:

 - react: https://codesandbox.io/s/422o58o3j4
 - preact: https://codesandbox.io/s/j9r725q2w
 - preact with workaround: https://codesandbox.io/s/6z431l219n

Notice that the subcomponent in the preact version is constantly remounting, if we hide/show the previous `<div>` while it's mounted only once in React. I found a workaround by setting a `key` prop to identify the `<div>`s.

**Comment by developit** [comment]
Interesting! Seems similar to #747, though the fact that it's triggering lifecycle makes it sound like it's an index/offset miscalculation.

**Comment by youknowriad** [comment]
@developit the comment in this line https://github.com/developit/preact/blob/master/src/vdom/diff.js#L206 explains exactly the problem here IMO, preact is diffing to a previous node with the same type ('div') while react is taking the `children` and probably `props` into account to find the corresponding node.

**Comment by Kanaye** [comment]
I looked a few minutes into this and yes that 's excatly what  's happening.
Preact updates the first dom node because it 's the same nodeType as the second node and then remove the other. Also when adding the node again preact will update the first node (remove the children) and then create a second node with a new component.

On first render the DOM will look like this:
```html
<div></div>
<div>
    <div>Sub Component Mounted:1</div>
</div>
```

While rerendering/diffing preact will create a new component and update the DOM to this (state _while_ diffing, *before* node removal):
```html
<div>
    <div>
        <div>Sub Component Mounted:2</div>
    </div>
    <div>
        <div>Sub Component Mounted:1</div>
    </div>
</div>
```
Then the second div will be removed and so on.

I'm not sure yet what would be a performant solution for this.
Just taking the length of the children into account wouldn't fix this in all cases.

**Comment by localvoid** [comment]
> while react is taking the children and probably props into account to find the corresponding node.

React just assigns implicit keys for all nodes https://twitter.com/sebmarkbage/status/892977689430171649

**Comment by developit** [comment]
Not sure it's possible within `isSameNodeType` since it doesn't have the right information (parent node). It's odd, Preact uses empty Text nodes to mirror "holes" in VDOM (empty values resulting from conditionals), but in this case that doesn't seem to be working.  I've been staring at the diff for a bit too long though, I'm going to have to step through the example to see where the index is being mismatched.

**Comment by Kanaye** [comment]
Hmm, you 're right, I missed the "placeholder" text nodes.
With those taken into account there is probably a better way to handle this.

With this taken into account the problem get 's a liitle more clear:

After adding the text node the `dom.childNodes` will look like this:
```javascript
[
    #textNode, // just inserted
    div, // the empty div that needs to be removed
    div // the div with the component
]
```

The [children array](https://github.com/developit/preact/blob/2205c0f65d9595df1b1fddd7b09c79102ae34401/src/vdom/diff.js#L209) still looks like this:
```
[
    div, // the empty div preact will incorrectly update/render into
    div // the div with the component
]
```
Because preact doesn't "know" that the first div is "replaced" and `min` is still `0`,  `isSameNodeType` will update the first node and the last one will be removed later.

Maybe searching in the children array from the index of the element and falling back to min could be an option. But that would require to change the logic to remove the unused nodes.

Also replacing dom nodes with placeholder nodes and counting up `min` could be an option.
But I have to think more about edge cases where this could break.

**Comment by developit** [comment]
Excellent overview @Kanaye. The tricky part here is that it's not possible to search for a match ahead-of-time, since that would require rendering the remaining virtual children and doing so requires obtaining a likely match.

I think you're on to something though, if the diff sees that there are more virtual children than children, it should only ever insert rather than consuming the next element.  I might take a stab at how that might look tonight.

**Comment by Kanaye** [comment]
Okay, this is trickier then I initialy thought.
Skipping nodes just based on the count of child nodes doesn't work.
example:
```html
<div>
   <div><div></div></div><!-- div from example above with one more child -->
   <div><div>...</div></div><!-- div with component -->
</div>
```
With this example we would face the same issue when just taking the child node count into account.
But as you already wrote, it 's not possible to search ahead. 

Maybe consuming placeholder nodes and consuming the first child node when the vnode is a placeholder could work.

So in case the vchild is an empty string we would consume the first node in children.
Or if the first Node is a text node without content.

So the condition for that would look somthing like this:
```javascript
(vchild==='' || node.splitText!==undefined && node.nodeValue==='')
```

I couldn't think of a case where this would break, except the zero-width-space SSR workarround.
But I probably missed something.

What do you think ?

**Comment by developit** [comment]
I believe we used to use Comment nodes as empty component root placeholders, maybe that would be a quicker check than `nodeValue===''`? It'd require dropping the splitText() optimization and some more logic in the diff to remove comments.

**Comment by Kanaye** [comment]
I thought about using comment nodes instead, but I wasn't sure if there 's a reason why they aren't used.
I'll take a look at the commit log and performance test a bit within the next few days.

**Comment by lemmy-** [comment]
Guuuys, is anyone trying to fix this issue?

**Comment by Kanaye** [comment]
I've got finaly time to look into this again.
I 've created 2 versions of this one using comment nodes as placeholder nodes and one using textnodes.
* [Comment Node](https://github.com/developit/preact/compare/master...Kanaye:dom-node-selection-%23857-comment)
* [Text Node](https://github.com/Kanaye/preact/tree/dom-node-selection-%23857-text)

After [short profiling](https://esbench.com/bench/5a6e560b9f9721009fe9c8c9), it looks like the text node version is faster. 
But I'm using because this looks like the [fastest way](https://esbench.com/bench/5a018c2e99634800a03493f1) is (at least cross browser) `nodeType` .

@developit if you are aware of faster methods to detected comment nodes, I'd like to try them out :)

Also the textnode version is smaller (3455 bytes gziped) compared to the comment node version (3488 bytes) but booth aren 't realy optimized. These branches are "proof of concept"-ish.

**Comment by yaodingyd** [comment]
@azizhk Implicit keys for all vnodes sounds like a good idea. It might be a bit challenging to implement as Preact needs to keep a minimum file size. A PR is always welcome?

**Comment by marvinhagemeister** [comment]
Related #1440
