### ISSUE TITLE
Preact with Kea?

### ISSUE THREAD

**Issue by hwclass** [developit/preact#863]
Hi folks,

There is already a framework(ish) thingy based on redux called Kea and it simplifies connecting state with HoC(s). Is there any examples or gists you have about integrating those?

Cheers

Baris

**Comment by Kanaye** [comment]
Hi @hwclass,

I 've just tested there [kae-example](https://github.com/keajs/kea-example) with preact and it works just fine.
All you need todo is:
1. clone there example run `npm i --save-dev`
2. `npm i --save-dev preact preact-compat`
3. add 
     ```javascript
     'react': 'preact-compat',
     'react-dom': 'preact-compat'
     ```
   to the `alias`-section of their `webpack.config.js`.

Now everything works just like when using react.

**Comment by hwclass** [comment]
Thanks @Kanaye, I'll look at it ;)

**Comment by Kanaye** [comment]
Hi @hwclass.
To start a new project with preact and keajs you just need keajs (and it 's dependencies excluding react), preact and preact-compat.

Imagine that we have a new project with webpack, babel and all the other stuff you need already installed as dev dependencies. 
Run `npm install --save preact preact-compat kea react-redux redux reselect prop-types` to add preact, preact-compat, kea and it 's dependencies.
npm will warn you that react is missing but because we replace react with preact-compat we can just ignore this warning.

In the webpack configuration we will need an [alias](https://webpack.js.org/configuration/resolve/#resolve-alias) section and need to add
```javascript
'react': 'preact-compat',
'react-dom': 'preact-compat'
```
to it.
This will tell webpack to use `preact-compat` whereever `kea` or `react-redux` will import (or require) `react`.

Know you can use kae with preact just as you woul use it with react.

I haven't used kea before but I tried this config with there [counter example](https://kea.js.org/guide/counter).

You can find this test [here](https://kanaye.github.io/preact-kea-counter-example/) and the repository with everything I did [here](https://github.com/Kanaye/preact-kea-counter-example)

**Comment by marvinhagemeister** [comment]
That's awesome, seems like you already found a solution 👍
