### ISSUE TITLE
Webpack Bublé

### ISSUE THREAD

**Issue by allexon** [developit/preact#895]
Hello, if someone helps: I'm trying to set up Bublé, to do the JS and JSX transpiler, I do not know where exactly this code is placed: buble ({jsx: 'h'})

for the bublé to run with preact! what should I do in the code below, which does not work, does not identify the bublé?

{
      test: /. js $ /, loaders: 'buble-loader', exclude: / node_modules /, include:
      Path.join (BIFAO_COMPONENTS),
                 query: {
                     objectAssign: 'Object.assign',
                     transforms: {dangerousTaggedTemplateString: true},
                     options: [buble ({jsx: 'h'}]]
                 }
},

**Comment by AbdulrahmanEng** [comment]
Place it in the 'plugins' array inside of the config file:

```
plugins: [
    buble({ jsx: 'h' }),
...
]
```

**Comment by allexon** [comment]
I had already done it this way too! The question is where is the name coming from: Buble? Do I need to install anything yarn add?
![buble](https://user-images.githubusercontent.com/1206288/30773902-94bed494-a050-11e7-99c5-98076e2a6cca.gif)

**Comment by heromen** [comment]
Why buble??? try babel

**Comment by developit** [comment]
This question would be much better asked on StackOverflow, since it has nothing to do with Preact.  You're looking for [buble-loader](https://github.com/sairion/buble-loader), and it's not a plugin.  It's possible you're conflating webpack configuration with rollup configuration, the two are quite different.
