### ISSUE TITLE
Element is not recreated if its key has changed

### ISSUE THREAD

**Issue by z-vr** [developit/preact#941]
I want to completely destroy an element if its key has changed.

Preact does not allow to do that: [proof](https://codesandbox.io/s/427mqqmr19). React, on the other hand, does handle the key change properly by recreating whole element [codesandbox](https://codesandbox.io/s/24y0z5w5mr).

**Comment by vaishalshah** [comment]
@z-vr From what it seems like, `key` prop comparison only happens in case of children node update. Since in your example, `div className='selector'` is a parent node, it is not recreated and instead reused. If you wrap your `div className='selector'` inside another empty `div`, it works same as React and is being recreated.

The idea behind `key` prop comparison might be that it is useful when you want to mutate array of children where the order of children might be different like `<li>`. I have seen @developit saying multiple times that he wants to reuse dom elements as much as possible and since in your use case, dom node type (div) isn't changed there is no need to recreate that dom element.

**Comment by developit** [comment]
We do try to reuse elements, but now that recycling is gone this probably counts as a bug.  In React, changing the `key` triggers a delete + recreate.  In preact, it will only remount a child component.

**Comment by marvinhagemeister** [comment]
Good news: Just checked with the code that's in `master` right now and I can't reproduce the issue anymore :tada:
